### PR TITLE
Error by GPS.begin() function

### PR DESCRIPTION
**Pull request by thekunalsaini**
GPS_MODE_SHIELD without monitoring error by GPS.begin() function

### CODE REVIEW

**Review by per1234 — CHANGES_REQUESTED** [review]
Please fix the indentation.

Please remove the trailing spaces you left.

**Review by thekunalsaini — COMMENTED** [review]
Sir, Please review @per1234

**Comment by thekunalsaini** [comment]
Hi @per1234 ,
Sir a lot of thanks to you because you teach us a lot.
Thanks again.
Please review the required changes.

**Comment by aentinger** [comment]
I've got really no idea what this is fixing, I can't see an error in the original implementation, closing.

**Pull request closed without merging**
